FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git

# install air (PINNED)
RUN go install github.com/air-verse/air@v1.52.3

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air"]
